#!/data/data/com.termux/files/usr/bin/bash
# AUTO-GENERATED by omega_spawn_engine.py
# Node: omega-node-003
# Spawned: 2026-06-09T19:12:43.688108
# Generation: 1

NODE_ID="omega-node-003"
CONSENSUS_PORT=7436
MESH_PORT=7437
LOG_DIR="/data/data/com.termux/files/home/omega_runtime/logs"

echo "[$(date)] Spawning $NODE_ID..."

# Start consensus node
nohup python3 /data/data/com.termux/files/home/Omega-Production/omega_consensus.py \
    --node-id "$NODE_ID" \
    --port "$CONSENSUS_PORT" \
    >> "$LOG_DIR/omega-node-003_consensus.log" 2>&1 &
echo "[$(date)] Consensus PID=$!"

# Start mesh node
nohup python3 /data/data/com.termux/files/home/Omega-Production/omega_node_manager.py \
    --node-id "$NODE_ID" \
    --port "$MESH_PORT" \
    >> "$LOG_DIR/omega-node-003_mesh.log" 2>&1 &
echo "[$(date)] Mesh PID=$!"

echo "[$(date)] $NODE_ID spawned successfully"
