#!/data/data/com.termux/files/usr/bin/bash
# AUTO-GENERATED by omega_spawn_engine.py
# Node: omega-node-006
# Spawned: 2026-06-23T19:07:41.140164
# Generation: 4

NODE_ID="omega-node-006"
CONSENSUS_PORT=7442
MESH_PORT=7443
LOG_DIR="/data/data/com.termux/files/home/omega_runtime/logs"

echo "[$(date)] Spawning $NODE_ID..."

# Start consensus node
nohup python3 /data/data/com.termux/files/home/Omega-Production/omega_consensus.py \
    --node-id "$NODE_ID" \
    --port "$CONSENSUS_PORT" \
    >> "$LOG_DIR/omega-node-006_consensus.log" 2>&1 &
echo "[$(date)] Consensus PID=$!"

# Start mesh node
nohup python3 /data/data/com.termux/files/home/Omega-Production/omega_node_manager.py \
    --node-id "$NODE_ID" \
    --port "$MESH_PORT" \
    >> "$LOG_DIR/omega-node-006_mesh.log" 2>&1 &
echo "[$(date)] Mesh PID=$!"

echo "[$(date)] $NODE_ID spawned successfully"
