#!/data/data/com.termux/files/usr/bin/bash
# AUTO-GENERATED by omega_spawn_engine.py
# Node: omega-node-001
# Spawned: 2026-06-23T14:17:27.895215
# Generation: -1

NODE_ID="omega-node-001"
CONSENSUS_PORT=7432
MESH_PORT=7433
LOG_DIR="/data/data/com.termux/files/home/omega_runtime/logs"

echo "[$(date)] Spawning $NODE_ID..."

# Start consensus node
nohup python3 /data/data/com.termux/files/home/Omega-Production/omega_consensus.py \
    --node-id "$NODE_ID" \
    --port "$CONSENSUS_PORT" \
    >> "$LOG_DIR/omega-node-001_consensus.log" 2>&1 &
echo "[$(date)] Consensus PID=$!"

# Start mesh node
nohup python3 /data/data/com.termux/files/home/Omega-Production/omega_node_manager.py \
    --node-id "$NODE_ID" \
    --port "$MESH_PORT" \
    >> "$LOG_DIR/omega-node-001_mesh.log" 2>&1 &
echo "[$(date)] Mesh PID=$!"

echo "[$(date)] $NODE_ID spawned successfully"
